        REAL WEIGHT,TOTAL,AVERAG
        INTEGER PERSON
        DIMENSION WEIGHT(10)
        TOTAL=0.0
        DO 100 PERSON=1,10
            READ *,WEIGHT(PERSON)
            TOTAL = TOTAL + WEIGHT(PERSON)
100     CONTINUE
        AVERAG = TOTAL / 10
        PRINT *,' SUM OF NUMBERS IS ',TOTAL
        PRINT *,' AVERAGE WEIGHT IS ',AVERAG
        PRINT *,' 10 WEIGHTS WERE '
        DO 200 PERSON=1,10
            PRINT *,WEIGHT(PERSON)
200     CONTINUE
        END